// Trims verbatim Goodreads series-page HTML mocks (test/fixtures/verbatim/*.html)
// down to the structural skeleton the userscript actually reads, and writes
// the result to test/fixtures/skeletons/<same-name>.html.
//
// Selectors retained from the page (see goodreads-extract-series.user.js):
//   1. .responsiveSeriesHeader__title h1  -> fallback series name
//   2. [data-react-class="ReactComponents.SeriesHeader"] -> props.title
//   3. [data-react-class="ReactComponents.SeriesList"]   -> props.series / seriesHeaders
//   4. .seriesTeaserBox -> optional sentinel the userscript must ignore
//
// The skeleton keeps #1 (with its h1), #2 and #3 as empty divs with their
// parsed data-react-props JSON payload, and #4 as an empty stub. The payload is
// preserved, but the generated HTML is not byte-for-byte identical to the
// source page.
//
// Run: bun run trim:mocks
// Idempotent: re-running on a skeleton yields the same bytes.

const fs = require('fs');
const path = require('path');
const { Window } = require('happy-dom');

const ROOT = path.resolve(__dirname, '..');
const FIXTURE_DIR = path.join(ROOT, 'test', 'fixtures');
const VERBATIM_DIR = path.join(FIXTURE_DIR, 'verbatim');
const OUT_DIR = path.join(FIXTURE_DIR, 'skeletons');

function parseDoc(html) {
  const win = new Window();
  win.document.write(html);
  return win.document;
}

function reactElSkeleton(el) {
  const cls = el.getAttribute('data-react-class');
  const props = el.getAttribute('data-react-props');
  const propsAttr = props != null
    ? ' data-react-props="' + props.replace(/"/g, '&quot;') + '"'
    : '';
  return '<div data-react-class="' + cls + '"' + propsAttr + '></div>';
}

function headerTitleSkeleton(doc) {
  const el = doc.querySelector('.responsiveSeriesHeader__title');
  if (!el) return '';
  const h1 = el.querySelector('h1');
  const text = h1 ? h1.textContent.trim() : '';
  return '<div class="responsiveSeriesHeader__title"><h1>' + text + '</h1></div>';
}

function trimOne(file) {
  const src = path.join(VERBATIM_DIR, file);
  const dst = path.join(OUT_DIR, file);
  const beforeBytes = fs.statSync(src).size;
  const html = fs.readFileSync(src, 'utf8');
  const doc = parseDoc(html);

  const lines = [];
  lines.push('<!-- skeleton generated by scripts/trim-mocks.js from test/fixtures/verbatim/' + file + ' -->');
  lines.push('<!-- DO NOT EDIT by hand; regenerate via `bun run trim:mocks` -->');

  const title = headerTitleSkeleton(doc);
  if (title) lines.push(title);

  const headers = Array.from(doc.querySelectorAll('[data-react-class="ReactComponents.SeriesHeader"]'));
  const lists = Array.from(doc.querySelectorAll('[data-react-class="ReactComponents.SeriesList"]'));
  headers.forEach((el) => lines.push(reactElSkeleton(el)));
  lists.forEach((el) => lines.push(reactElSkeleton(el)));

  if (doc.querySelector('.seriesTeaserBox')) {
    lines.push('<div class="seriesTeaserBox"></div>');
  }

  const out = lines.join('\n') + '\n';
  fs.writeFileSync(dst, out, 'utf8');
  const afterBytes = Buffer.byteLength(out, 'utf8');
  console.log(
    file + ': ' +
    (beforeBytes / 1024).toFixed(1) + 'KB -> ' +
    (afterBytes / 1024).toFixed(1) + 'KB ' +
    '(header: ' + headers.length + ', lists: ' + lists.length + ', ' +
    (title ? 'has-h1' : 'no-h1') + ', ' +
    (doc.querySelector('.seriesTeaserBox') ? 'has-teaser' : 'no-teaser') + ')'
  );
}

const files = fs
  .readdirSync(VERBATIM_DIR)
  .filter((f) => /\.html$/.test(f))
  .sort();

if (files.length === 0) {
  console.error('No verbatim mocks found in ' + VERBATIM_DIR);
  process.exit(1);
}

console.log('Trimming ' + files.length + ' mock(s):');
for (const f of files) trimOne(f);
console.log('Done.');
